// Mocks generated by Mockito 5.4.5 from annotations
// in tmdb/test/presentation/blocs/person_images_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tmdb/data/repositories/person_details_repository.dart' as _i2;
import 'package:tmdb/domain/entities/person_image.dart' as _i5;
import 'package:tmdb/domain/use_cases/get_cached_person_images.dart' as _i6;
import 'package:tmdb/domain/use_cases/get_person_images.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePersonDetailsRepository_0 extends _i1.SmartFake
    implements _i2.PersonDetailsRepository {
  _FakePersonDetailsRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetPersonImages].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPersonImages extends _i1.Mock implements _i3.GetPersonImages {
  MockGetPersonImages() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PersonDetailsRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakePersonDetailsRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.PersonDetailsRepository);

  @override
  _i4.Future<List<_i5.PersonImage>> call(int? id) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [id],
        ),
        returnValue:
            _i4.Future<List<_i5.PersonImage>>.value(<_i5.PersonImage>[]),
      ) as _i4.Future<List<_i5.PersonImage>>);
}

/// A class which mocks [GetCachedPersonImages].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCachedPersonImages extends _i1.Mock
    implements _i6.GetCachedPersonImages {
  MockGetCachedPersonImages() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PersonDetailsRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakePersonDetailsRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.PersonDetailsRepository);

  @override
  _i4.Future<List<_i5.PersonImage>> call(int? id) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [id],
        ),
        returnValue:
            _i4.Future<List<_i5.PersonImage>>.value(<_i5.PersonImage>[]),
      ) as _i4.Future<List<_i5.PersonImage>>);
}
