// Mocks generated by Mockito 5.4.5 from annotations
// in tmdb/test/domain/use_cases/get_person_images_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tmdb/data/data_sources/tmdb_api.dart' as _i2;
import 'package:tmdb/data/models/person_details_model.dart' as _i3;
import 'package:tmdb/data/models/person_image_model.dart' as _i6;
import 'package:tmdb/data/repositories/person_details_repository.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTmdbApi_0 extends _i1.SmartFake implements _i2.TmdbApi {
  _FakeTmdbApi_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePersonDetailsModel_1 extends _i1.SmartFake
    implements _i3.PersonDetailsModel {
  _FakePersonDetailsModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PersonDetailsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPersonDetailsRepository extends _i1.Mock
    implements _i4.PersonDetailsRepository {
  MockPersonDetailsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TmdbApi get tmdbApi => (super.noSuchMethod(
        Invocation.getter(#tmdbApi),
        returnValue: _FakeTmdbApi_0(
          this,
          Invocation.getter(#tmdbApi),
        ),
      ) as _i2.TmdbApi);

  @override
  _i5.Future<_i3.PersonDetailsModel> getPersonDetails(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPersonDetails,
          [id],
        ),
        returnValue:
            _i5.Future<_i3.PersonDetailsModel>.value(_FakePersonDetailsModel_1(
          this,
          Invocation.method(
            #getPersonDetails,
            [id],
          ),
        )),
      ) as _i5.Future<_i3.PersonDetailsModel>);

  @override
  _i5.Future<_i3.PersonDetailsModel?> getCachedPersonDetails(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedPersonDetails,
          [id],
        ),
        returnValue: _i5.Future<_i3.PersonDetailsModel?>.value(),
      ) as _i5.Future<_i3.PersonDetailsModel?>);

  @override
  _i5.Future<List<_i6.PersonImageModel>> getPersonImages(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPersonImages,
          [id],
        ),
        returnValue: _i5.Future<List<_i6.PersonImageModel>>.value(
            <_i6.PersonImageModel>[]),
      ) as _i5.Future<List<_i6.PersonImageModel>>);

  @override
  _i5.Future<List<_i6.PersonImageModel>> getCachedPersonImages(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedPersonImages,
          [id],
        ),
        returnValue: _i5.Future<List<_i6.PersonImageModel>>.value(
            <_i6.PersonImageModel>[]),
      ) as _i5.Future<List<_i6.PersonImageModel>>);
}
