// Mocks generated by Mockito 5.4.5 from annotations
// in tmdb/test/domain/use_cases/get_popular_people_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tmdb/data/data_sources/tmdb_api.dart' as _i2;
import 'package:tmdb/data/models/person_model.dart' as _i5;
import 'package:tmdb/data/repositories/person_repository.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTmdbApi_0 extends _i1.SmartFake implements _i2.TmdbApi {
  _FakeTmdbApi_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PersonRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPersonRepository extends _i1.Mock implements _i3.PersonRepository {
  MockPersonRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TmdbApi get tmdbApi => (super.noSuchMethod(
        Invocation.getter(#tmdbApi),
        returnValue: _FakeTmdbApi_0(
          this,
          Invocation.getter(#tmdbApi),
        ),
      ) as _i2.TmdbApi);

  @override
  _i4.Future<List<_i5.PersonModel>> getPopularPeople({int? page = 1}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPopularPeople,
          [],
          {#page: page},
        ),
        returnValue:
            _i4.Future<List<_i5.PersonModel>>.value(<_i5.PersonModel>[]),
      ) as _i4.Future<List<_i5.PersonModel>>);

  @override
  _i4.Future<List<_i5.PersonModel>> getCachedPopularPeople() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedPopularPeople,
          [],
        ),
        returnValue:
            _i4.Future<List<_i5.PersonModel>>.value(<_i5.PersonModel>[]),
      ) as _i4.Future<List<_i5.PersonModel>>);

  @override
  _i4.Future<Map<String, dynamic>> getPersonDetails(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPersonDetails,
          [id],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<List<String>> getPersonImages(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getPersonImages,
          [id],
        ),
        returnValue: _i4.Future<List<String>>.value(<String>[]),
      ) as _i4.Future<List<String>>);
}
