// Mocks generated by Mockito 5.4.5 from annotations
// in tmdb/test/presentation/screens/home_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:flutter_bloc/flutter_bloc.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:tmdb/domain/use_cases/get_cached_popular_people.dart' as _i4;
import 'package:tmdb/domain/use_cases/get_popular_people.dart' as _i3;
import 'package:tmdb/presentation/blocs/popular_persons/popular_people_bloc.dart'
    as _i2;

import 'home_screen_test.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePopularPeopleState_0 extends _i1.SmartFake
    implements _i2.PopularPeopleState {
  _FakePopularPeopleState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetPopularPeople_1 extends _i1.SmartFake
    implements _i3.GetPopularPeople {
  _FakeGetPopularPeople_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetCachedPopularPeople_2 extends _i1.SmartFake
    implements _i4.GetCachedPopularPeople {
  _FakeGetCachedPopularPeople_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MockPopularPeopleBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockPopularPeopleBloc extends _i1.Mock
    implements _i5.MockPopularPeopleBloc {
  MockMockPopularPeopleBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PopularPeopleState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakePopularPeopleState_0(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.PopularPeopleState);

  @override
  _i6.Stream<_i2.PopularPeopleState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i6.Stream<_i2.PopularPeopleState>.empty(),
      ) as _i6.Stream<_i2.PopularPeopleState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  _i3.GetPopularPeople get getPopularPeople => (super.noSuchMethod(
        Invocation.getter(#getPopularPeople),
        returnValue: _FakeGetPopularPeople_1(
          this,
          Invocation.getter(#getPopularPeople),
        ),
      ) as _i3.GetPopularPeople);

  @override
  _i4.GetCachedPopularPeople get getCachedPopularPeople => (super.noSuchMethod(
        Invocation.getter(#getCachedPopularPeople),
        returnValue: _FakeGetCachedPopularPeople_2(
          this,
          Invocation.getter(#getCachedPopularPeople),
        ),
      ) as _i4.GetCachedPopularPeople);

  @override
  void emit(_i2.PopularPeopleState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i7.Change<_i2.PopularPeopleState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void add(_i2.PopularPeopleEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i2.PopularPeopleEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i2.PopularPeopleEvent>(
    _i7.EventHandler<E, _i2.PopularPeopleState>? handler, {
    _i7.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i7.Transition<_i2.PopularPeopleEvent, _i2.PopularPeopleState>?
              transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );
}
