name: Test

on:
  push:

jobs:
  test:
    name: Run test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
        #  flutter-version: '3.3.10'
          channel: 'stable'
      - name: Create .env file
        run: |
         echo "API_URL=https://dummy.api" >> .env
      - name: Run pub get
        run: flutter pub get
      - name: Run test
        run: flutter test

  
